// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: args.proto

#ifndef PROTOBUF_INCLUDED_args_2eproto
#define PROTOBUF_INCLUDED_args_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_args_2eproto 

namespace protobuf_args_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_args_2eproto
class Argument;
class ArgumentDefaultTypeInternal;
extern ArgumentDefaultTypeInternal _Argument_default_instance_;
class ArgumentList;
class ArgumentListDefaultTypeInternal;
extern ArgumentListDefaultTypeInternal _ArgumentList_default_instance_;
class Request;
class RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
namespace google {
namespace protobuf {
template<> ::Argument* Arena::CreateMaybeMessage<::Argument>(Arena*);
template<> ::ArgumentList* Arena::CreateMaybeMessage<::ArgumentList>(Arena*);
template<> ::Request* Arena::CreateMaybeMessage<::Request>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class Argument : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Argument) */ {
 public:
  Argument();
  virtual ~Argument();

  Argument(const Argument& from);

  inline Argument& operator=(const Argument& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Argument(Argument&& from) noexcept
    : Argument() {
    *this = ::std::move(from);
  }

  inline Argument& operator=(Argument&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Argument& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Argument* internal_default_instance() {
    return reinterpret_cast<const Argument*>(
               &_Argument_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Argument* other);
  friend void swap(Argument& a, Argument& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Argument* New() const final {
    return CreateMaybeMessage<Argument>(NULL);
  }

  Argument* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Argument>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Argument& from);
  void MergeFrom(const Argument& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Argument* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .google.protobuf.Any value = 1;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 1;
  private:
  const ::google::protobuf::Any& _internal_value() const;
  public:
  const ::google::protobuf::Any& value() const;
  ::google::protobuf::Any* release_value();
  ::google::protobuf::Any* mutable_value();
  void set_allocated_value(::google::protobuf::Any* value);

  // @@protoc_insertion_point(class_scope:Argument)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::Any* value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_args_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ArgumentList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ArgumentList) */ {
 public:
  ArgumentList();
  virtual ~ArgumentList();

  ArgumentList(const ArgumentList& from);

  inline ArgumentList& operator=(const ArgumentList& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ArgumentList(ArgumentList&& from) noexcept
    : ArgumentList() {
    *this = ::std::move(from);
  }

  inline ArgumentList& operator=(ArgumentList&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ArgumentList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ArgumentList* internal_default_instance() {
    return reinterpret_cast<const ArgumentList*>(
               &_ArgumentList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ArgumentList* other);
  friend void swap(ArgumentList& a, ArgumentList& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ArgumentList* New() const final {
    return CreateMaybeMessage<ArgumentList>(NULL);
  }

  ArgumentList* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ArgumentList>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ArgumentList& from);
  void MergeFrom(const ArgumentList& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ArgumentList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Argument args = 1;
  int args_size() const;
  void clear_args();
  static const int kArgsFieldNumber = 1;
  ::Argument* mutable_args(int index);
  ::google::protobuf::RepeatedPtrField< ::Argument >*
      mutable_args();
  const ::Argument& args(int index) const;
  ::Argument* add_args();
  const ::google::protobuf::RepeatedPtrField< ::Argument >&
      args() const;

  // @@protoc_insertion_point(class_scope:ArgumentList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Argument > args_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_args_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Request) */ {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(Request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Request* other);
  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Request* New() const final {
    return CreateMaybeMessage<Request>(NULL);
  }

  Request* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Request>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ArgumentList argslist = 2;
  int argslist_size() const;
  void clear_argslist();
  static const int kArgslistFieldNumber = 2;
  ::ArgumentList* mutable_argslist(int index);
  ::google::protobuf::RepeatedPtrField< ::ArgumentList >*
      mutable_argslist();
  const ::ArgumentList& argslist(int index) const;
  ::ArgumentList* add_argslist();
  const ::google::protobuf::RepeatedPtrField< ::ArgumentList >&
      argslist() const;

  // string url = 1;
  void clear_url();
  static const int kUrlFieldNumber = 1;
  const ::std::string& url() const;
  void set_url(const ::std::string& value);
  #if LANG_CXX11
  void set_url(::std::string&& value);
  #endif
  void set_url(const char* value);
  void set_url(const char* value, size_t size);
  ::std::string* mutable_url();
  ::std::string* release_url();
  void set_allocated_url(::std::string* url);

  // @@protoc_insertion_point(class_scope:Request)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ArgumentList > argslist_;
  ::google::protobuf::internal::ArenaStringPtr url_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_args_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Argument

// .google.protobuf.Any value = 1;
inline bool Argument::has_value() const {
  return this != internal_default_instance() && value_ != NULL;
}
inline const ::google::protobuf::Any& Argument::_internal_value() const {
  return *value_;
}
inline const ::google::protobuf::Any& Argument::value() const {
  const ::google::protobuf::Any* p = value_;
  // @@protoc_insertion_point(field_get:Argument.value)
  return p != NULL ? *p : *reinterpret_cast<const ::google::protobuf::Any*>(
      &::google::protobuf::_Any_default_instance_);
}
inline ::google::protobuf::Any* Argument::release_value() {
  // @@protoc_insertion_point(field_release:Argument.value)
  
  ::google::protobuf::Any* temp = value_;
  value_ = NULL;
  return temp;
}
inline ::google::protobuf::Any* Argument::mutable_value() {
  
  if (value_ == NULL) {
    auto* p = CreateMaybeMessage<::google::protobuf::Any>(GetArenaNoVirtual());
    value_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Argument.value)
  return value_;
}
inline void Argument::set_allocated_value(::google::protobuf::Any* value) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(value_);
  }
  if (value) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, value, submessage_arena);
    }
    
  } else {
    
  }
  value_ = value;
  // @@protoc_insertion_point(field_set_allocated:Argument.value)
}

// -------------------------------------------------------------------

// ArgumentList

// repeated .Argument args = 1;
inline int ArgumentList::args_size() const {
  return args_.size();
}
inline void ArgumentList::clear_args() {
  args_.Clear();
}
inline ::Argument* ArgumentList::mutable_args(int index) {
  // @@protoc_insertion_point(field_mutable:ArgumentList.args)
  return args_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Argument >*
ArgumentList::mutable_args() {
  // @@protoc_insertion_point(field_mutable_list:ArgumentList.args)
  return &args_;
}
inline const ::Argument& ArgumentList::args(int index) const {
  // @@protoc_insertion_point(field_get:ArgumentList.args)
  return args_.Get(index);
}
inline ::Argument* ArgumentList::add_args() {
  // @@protoc_insertion_point(field_add:ArgumentList.args)
  return args_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Argument >&
ArgumentList::args() const {
  // @@protoc_insertion_point(field_list:ArgumentList.args)
  return args_;
}

// -------------------------------------------------------------------

// Request

// string url = 1;
inline void Request::clear_url() {
  url_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Request::url() const {
  // @@protoc_insertion_point(field_get:Request.url)
  return url_.GetNoArena();
}
inline void Request::set_url(const ::std::string& value) {
  
  url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Request.url)
}
#if LANG_CXX11
inline void Request::set_url(::std::string&& value) {
  
  url_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Request.url)
}
#endif
inline void Request::set_url(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Request.url)
}
inline void Request::set_url(const char* value, size_t size) {
  
  url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Request.url)
}
inline ::std::string* Request::mutable_url() {
  
  // @@protoc_insertion_point(field_mutable:Request.url)
  return url_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request::release_url() {
  // @@protoc_insertion_point(field_release:Request.url)
  
  return url_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_allocated_url(::std::string* url) {
  if (url != NULL) {
    
  } else {
    
  }
  url_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), url);
  // @@protoc_insertion_point(field_set_allocated:Request.url)
}

// repeated .ArgumentList argslist = 2;
inline int Request::argslist_size() const {
  return argslist_.size();
}
inline void Request::clear_argslist() {
  argslist_.Clear();
}
inline ::ArgumentList* Request::mutable_argslist(int index) {
  // @@protoc_insertion_point(field_mutable:Request.argslist)
  return argslist_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::ArgumentList >*
Request::mutable_argslist() {
  // @@protoc_insertion_point(field_mutable_list:Request.argslist)
  return &argslist_;
}
inline const ::ArgumentList& Request::argslist(int index) const {
  // @@protoc_insertion_point(field_get:Request.argslist)
  return argslist_.Get(index);
}
inline ::ArgumentList* Request::add_argslist() {
  // @@protoc_insertion_point(field_add:Request.argslist)
  return argslist_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ArgumentList >&
Request::argslist() const {
  // @@protoc_insertion_point(field_list:Request.argslist)
  return argslist_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_args_2eproto
